name: Ping Monitors Cron

on:
  schedule:
    - cron: "0 8 * * *" # every day at 8:00 AM UTC

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Ping API
        run: curl -s -o /dev/null -w "%{http_code}" "${{ secrets.PING_API_URL }}"
